kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: ingress-basic
data:
  proxy-connect-timeout: "10s"
  proxy-read-timeout: "10s"
  client-max-body-size: "2m"
  error-log-level: "debug"